### ISSUE TITLE
Making a debug build

### ISSUE THREAD

**Issue by alexgleason** [electric-sql/pglite#321]
Hi, I'm getting the following error when making queries:

```
RuntimeError: Aborted(). Build with -sASSERTIONS for more info.
    at abort (file:///home/alex/.cache/deno/npm/registry.npmjs.org/@soapbox.pub/pglite/0.2.11/dist/postgres.js:740:11)
    at __abort_js (file:///home/alex/.cache/deno/npm/registry.npmjs.org/@soapbox.pub/pglite/0.2.11/dist/postgres.js:7244:7)
    at abort (wasm://wasm/postgres.wasm-02856ac6:1:7189834)
    at errfinish (wasm://wasm/postgres.wasm-02856ac6:1:2120762)
    at InitWalRecovery (wasm://wasm/postgres.wasm-02856ac6:1:5426759)
    at StartupXLOG (wasm://wasm/postgres.wasm-02856ac6:1:5273250)
    at InitPostgres (wasm://wasm/postgres.wasm-02856ac6:1:625849)
    at AsyncPostgresSingleUserMain (wasm://wasm/postgres.wasm-02856ac6:1:2510013)
    at pg_initdb (wasm://wasm/postgres.wasm-02856ac6:1:3412565)
    at Object.Module._pg_initdb (file:///home/alex/.cache/deno/npm/registry.npmjs.org/@soapbox.pub/pglite/0.2.11/dist/postgres.js:10397:109)
```

What I want to know is, how can I produce a debug build to get more info? I tried editing linkweb.sh and linkexport.sh, changing `-sASSERTIONS=0` to `-sASSERTIONS`, but it seemed to have no effect. I'm using `pnpm wasm:build` and then publishing with `pnpm publish`.

My best guess is that maybe the database is getting corrupted when the process exits, but I want better proof than this traceback so I can do something to fix it.

**Comment by samwillis** [comment]
Hey @alexgleason 

Is this being thrown on a custom build or the published one? And roughly what's the sequence + environment that triggers it?

That change to the build args is one options, '-profiling' is the other as it stops the symbols being stripped/managed and so gives better stack traces.

I also find setting debug to 1 or 2 on the PGlite config is often enough as Postgres gives a good trace of what it's doing too.

**Comment by alexgleason** [comment]
Thank you @samwillis setting debug 5 gives me the info we need! I'll close this and open another issue.
