### ISSUE TITLE
RuntimeError with NodeJS on Windows

### ISSUE THREAD

**Issue by jgranduel** [electric-sql/pglite#34]
Thanks for this project.

I tried the basic kindof hello word you provide with NodeJS:
```
import { PGlite } from "@electric-sql/pglite";

const db = new PGlite();
await db.query("select 'Hello world' as message;");
// -> [ { message: "Hello world" } ]
```

tried in `Node REPL`, with no success using `import()`. So made a app.mjs file with same content. When I run `node app.mjs`, I got this runtime error :

```
> node .\app.mjs
file:///C:/temp/pglite-101/node_modules/@electric-sql/pglite/dist/chunk-Z6L7HPDY.js:95
          throw ex;
          ^

RuntimeError: Aborted(Error: ENOENT: no such file or directory, open 'C:\C:\temp\pglite-101\node_modules\@electric-sql\pglite\dist\postgres.wasm'). Build with -sASSERTIONS for more info.
    at abort (file:///C:/temp/pglite-101/node_modules/@electric-sql/pglite/dist/chunk-Z6L7HPDY.js:384:15)
    at getBinary (file:///C:/temp/pglite-101/node_modules/@electric-sql/pglite/dist/chunk-Z6L7HPDY.js:414:9)
    at file:///C:/temp/pglite-101/node_modules/@electric-sql/pglite/dist/chunk-Z6L7HPDY.js:439:16

Node.js v21.6.1
```

Note this strange `C:\C:\`.

**Comment by samwillis** [comment]
Thanks for the report, looks like I need to fire up a Windows VM to do some testing.

I suspect the error is somewhere in:

https://github.com/electric-sql/pglite/blob/543bdf1ae0b0e90f8a40200e8418bba4fe305f4f/packages/pglite/src/nodefs.ts#L9-L10

https://github.com/electric-sql/pglite/blob/543bdf1ae0b0e90f8a40200e8418bba4fe305f4f/packages/pglite/src/nodefs.ts#L41-L52

**Comment by jgranduel** [comment]
I got the same error after `npm install @electric-sql/pglite`
```
file:///C:/temp/2024/pglite/node_modules/@electric-sql/pglite/dist/chunk-Z6L7HPDY.js:95
          throw ex;
          ^
RuntimeError: Aborted(Error: ENOENT: no such file or directory, open 'C:\C:\temp\2024\pglite\node_modules\@electric-sql\pglite\dist\postgres.wasm'). Build with -sASSERTIONS for more info.
    at abort (file:///C:/temp/2024/pglite/node_modules/@electric-sql/pglite/dist/chunk-Z6L7HPDY.js:384:15)
    at getBinary (file:///C:/temp/2024/pglite/node_modules/@electric-sql/pglite/dist/chunk-Z6L7HPDY.js:414:9)
    at file:///C:/temp/2024/pglite/node_modules/@electric-sql/pglite/dist/chunk-Z6L7HPDY.js:439:16
```

is it too early for trying this way?
Thanks!

**Comment by samwillis** [comment]
@jgranduel you may have tried just (matter of minutes) before I published the new release. Could you try again?

**Comment by jgranduel** [comment]
Thanks. Here's the result of my today fresh install:

app.mjs
```
import { PGlite } from "@electric-sql/pglite";

const db = new PGlite();
let res = await db.query("select 'Hello world' as message;");
// -> [ { message: "Hello world" } ]

console.log(JSON.stringify( {res} ) )
```
```
PowerShel-7.4> node .\app.mjs
{"res":{"rows":[{"message":"Hello world"}],"fields":[{"name":"message","dataTypeID":25}],"affectedRows":0}}
```

So I think it's the expected result 😀! Thank you very much.
