### ISSUE TITLE
`language "plpgsql" does not exist` on Ubuntu Dev Container on Windows

### ISSUE THREAD

**Issue by ai** [electric-sql/pglite#465]
Hi. I got strange error when I tried to run my server on different environment.

```
anguage "plpgsql" does not exist at 2024-12-09 11:40:52
        at he.Fe (file:///workspaces/slowreader/node_modules/.pnpm/@electric-sql+pglite@0.2.14/node_modules/@electric-sql/pglite/dist/chunk-5L6BPGXX.js:1:17688)
        at he.rt (file:///workspaces/slowreader/node_modules/.pnpm/@electric-sql+pglite@0.2.14/node_modules/@electric-sql/pglite/dist/chunk-5L6BPGXX.js:1:15073)
        at he.parse (file:///workspaces/slowreader/node_modules/.pnpm/@electric-sql+pglite@0.2.14/node_modules/@electric-sql/pglite/dist/chunk-5L6BPGXX.js:1:13825)
        at I_.execProtocol (file:///workspaces/slowreader/node_modules/.pnpm/@electric-sql+pglite@0.2.14/node_modules/@electric-sql/pglite/dist/index.js:3:2424729)
        at async I_.o (file:///workspaces/slowreader/node_modules/.pnpm/@electric-sql+pglite@0.2.14/node_modules/@electric-sql/pglite/dist/chunk-Y4PL6ZOT.js:8:1846)
        at async file:///workspaces/slowreader/node_modules/.pnpm/@electric-sql+pglite@0.2.14/node_modules/@electric-sql/pglite/dist/chunk-Y4PL6ZOT.js:8:2474
```

[JS code](https://github.com/hplush/slowreader/blob/main/server/db/index.ts):

```js
import { PGlite } from '@electric-sql/pglite'
import { drizzle } from 'drizzle-orm/pglite'
import { migrate } from 'drizzle-orm/pglite/migrator'
import { join } from 'node:path'

import { config } from '../lib/config.ts'
import * as schema from './schema.ts'
export * from './schema.ts'

const MIGRATE_CONFIG = {
  migrationsFolder: join(import.meta.dirname, 'migrations')
}

export const db = drizzle(new PGlite('file://./db/pgdata'), { schema })
await migrate(db, MIGRATE_CONFIG)
```

The projects use [Dev Container with Ubuntu image](https://github.com/hplush/slowreader/blob/main/.devcontainer/Dockerfile) and works correctly on my laptop (with Fedora) but we are getting this issue on Windows machine.

We are also using pnpm if it is related.

**Comment by yacineb** [comment]
Do you reproduce the issue with `await db.exec(`
  CREATE EXTENSION IF NOT EXISTS plpgsql;
`);`  ran before migrate ?

**Comment by ai** [comment]
I don’t have such. But everything works on one machine without it.

Here is Drizzle migration files:

```sql
CREATE TABLE IF NOT EXISTS "sessions" (
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"id" serial PRIMARY KEY NOT NULL,
	"token" text NOT NULL,
	"usedAt" timestamp DEFAULT now() NOT NULL,
	"userId" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "users" (
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"id" text PRIMARY KEY NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "sessions" ADD CONSTRAINT "sessions_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sessionsUserIdx" ON "sessions" USING btree ("userId");

ALTER TABLE "users" ADD COLUMN "passwordHash" text;

ALTER TABLE "sessions" ADD COLUMN "clientId" text;
```

Do you know why I may need it on one machine and do not need on another?

**Comment by yacineb** [comment]
@ai which node version are you using ? and which CPU architecture. Those can help investigating why you have such a difference

**Comment by ai** [comment]
One machine (everything works):
- Host OS: Linux (Fedora 41)
- Dev Container OS: Ubuntu
- Hardware: x86

Second machine, where it is not working:
- Host OS: Windows
- Dev Container OS: the same Ubuntu
- Hardware: x86

![photo_2024-12-12_12-09-32](https://github.com/user-attachments/assets/0c914cbf-a03d-4412-9924-e64d97c3cc93)

**Comment by ai** [comment]
I started to have `language "plpgsql" does not exist` error too on my machine. Very strange.

But seems like we can close it.
